
[package]
name = "smoothie-rs"
version = "0.1.0"
edition = "2021"
build = "build.rs"

[dependencies]
clap = {version = "4.1.4 ", features = ["derive"] } # cli arg helper
color-eyre = "0.6.2" # error handling
ffprobe = "0.3.3"
open-file = "0.1.0"  # open file with default app
rand = "0.8.5"  # randomly choose from fruits for suffix
rfd = "0.11.0"  # open file dialog
which = "4.4.0" # Get-Command / where.exe / which alternative
# rustsynth = "0.2.1" # wrapper for VapourSynth.dll
rustsynth = {git = "https://github.com/animafps/rustsynth"}
rustsynth-derive = {git = "https://github.com/animafps/rustsynth"}

# json stuff
serde = "1.0.152" 
serde_derive = "1.0.152"
serde_json = "1.0.91"
#reqwest = {version = "0.11.14", features = ["json"]}
#tokio = { version = "1.25.0", features = ["full"]}
colored = "2.0.0"
enable-ansi-support = "0.2.1"
num-rational = "0.4.1"
anyhow = "1.0.69"
ureq = { version = "2.6.2", features = ["json"] }
cty = "0.2.2"
bindgen = "0.64.0"
min-max = "0.1.8"
kdam = "0.1.7"
indicatif = { version = "0.17.2", features = ["improved_unicode"] }
regex = "1.7.2"

[build-dependencies]
winres = "0.1" # give the exe an icon
cc = "1.0.79"  # for /src/windows.c

# --release make smol
[profile.release]
strip = true
opt-level = "s"
lto = true
codegen-units = 1
